---
name: follow stage branch
on:
  push:
    branches:
      - stage

jobs:
  follow-stage-branch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: rebase
      run: |
        git config --global user.email "automata@vecnos.com"
        git config --global user.name "automata"
        git checkout -b stage-features
        git push --set-upstream origin stage-features --force
